# CDSE TS Browser

This notebook serves to construct a geojson file to use in https://github.com/jonasViehweger/cdse-tsbrowser/

It also constructs direct links to single samples.

In [89]:
import json
import urllib

import disfor
import geopandas as gpd
import polars as pl

In [90]:
samples = gpd.read_parquet(disfor.get("samples.parquet"))
samples.fillna("", inplace=True)
labels = pl.read_parquet(disfor.get("labels.parquet")).with_columns(
    is_event=pl.col.start.dt.day() == pl.col.end.dt.day()
)
with disfor.get("classes.json").open() as f:
    classes_mapping = json.load(f)

In [54]:
classes_mapping

{'100': 'Healthy Vegetation',
 '110': 'Undisturbed Forest',
 '120': 'Revegetation',
 '121': 'With Trees (after clear cut)',
 '122': 'Canopy closing (after thinning/defoliation)',
 '123': 'Without Trees (shrubs and grasses, no reforestation visible)',
 '200': 'Disturbed',
 '210': 'Planned',
 '211': 'Clear Cut',
 '212': 'Thinning',
 '213': 'Forestry Mulching (Non Forest Vegetation Removal)',
 '220': 'Salvage',
 '221': 'After Biotic Disturbance',
 '222': 'After Abiotic Disturbance',
 '230': 'Biotic',
 '231': 'Bark Beetle (with decline)',
 '232': 'Gypsy Moth (temporary)',
 '240': 'Abiotic',
 '241': 'Drought',
 '242': 'Wildfire',
 '243': 'Wind',
 '244': 'Avalanche',
 '245': 'Flood'}

In [ ]:
campaign_setup = {
    "type": "FeatureCollection",
    "campaign": {
        "name": "DISFOR",
        "startDate": "2015-01-01",
        "endDate": "2025-01-01",
        "flagLabels": classes_mapping,
        "fields": [
            {
                "key": "sample_id",
                "label": "Sample ID",
                "type": "display",
                "required": True,
                "session_persistent": False,
            },
            {
                "key": "source",
                "label": "Source",
                "type": "display",
                "required": True,
                "session_persistent": False,
            },
            {
                "key": "cluster_id",
                "label": "Cluster ID",
                "type": "display",
                "required": True,
                "session_persistent": False,
            },
            {
                "key": "confidence",
                "label": "Confidence",
                "type": "select",
                "options": ["high", "medium", "low"],
                "required": True,
                "session_persistent": False,
            },
            {
                "key": "comment",
                "label": "Comment",
                "type": "text",
                "required": False,
                "session_persistent": False,
            },
            {
                "key": "interpreter",
                "label": "Interpreter",
                "type": "text",
                "required": True,
                "session_persistent": True,
            },
        ],
    },
    "features": [],
}

In [56]:
# single sample schema:
feature_example = {
    "type": "Feature",
    "geometry": {"type": "Point", "coordinates": ["lon", "lat"]},
    "properties": {
        "sample_id": None,
        "flags": {"2020-07-13": "1", "2021-08-02": "2"},
        "confidence": "High",
        "comment": "Clear bark beetle signal, recovery visible by 2021",
        "interpreter": "jdoe",
    },
}

In [57]:
samples

,sample_id,original_sample_id,interpreter,dataset,source,source_description,s2_tile,cluster_id,cluster_description,comment,confidence,geometry
0,0,0,vij,1,EFFIS,"Evoland Project, EFFIS Source of Wildfire Poly...",30SUF,0.0,Damage polygons,"border, thinning, then clear cut",high,POINT (-4.12212 36.74179)
1,1,1,vij,1,EFFIS,"Evoland Project, EFFIS Source of Wildfire Poly...",30SUF,1.0,Damage polygons,"unclear progression, edge",medium,POINT (-4.12161 36.74231)
2,2,2,vij,1,EFFIS,"Evoland Project, EFFIS Source of Wildfire Poly...",30SUF,2.0,Damage polygons,plantation,high,POINT (-4.1192 36.74203)
3,3,3,vij,1,EFFIS,"Evoland Project, EFFIS Source of Wildfire Poly...",30SUF,3.0,Damage polygons,plantation,high,POINT (-4.12845 36.75831)
4,4,4,vij,1,EFFIS,"Evoland Project, EFFIS Source of Wildfire Poly...",30SUF,5.0,Damage polygons,clear cut,high,POINT (-4.12816 36.75908)
...,...,...,...,...,...,...,...,...,...,...,...,...
3823,3818,16066,vij,3,FORWIND + Copernicus Emergency Service,https://mapping.emergency.copernicus.eu/activa...,,SI20200205,"Id of the Event, given as ISO2 + Date of storm",,high,POINT (14.39175 46.2299)
3824,3819,16067,vij,3,FORWIND + Copernicus Emergency Service,https://mapping.emergency.copernicus.eu/activa...,,SI20200205,"Id of the Event, given as ISO2 + Date of storm",unclear salvage,high,POINT (14.4004 46.2291)
3825,3820,16070,vij,3,FORWIND + Copernicus Emergency Service,https://mapping.emergency.copernicus.eu/activa...,,SI20200205,"Id of the Event, given as ISO2 + Date of storm",,high,POINT (14.39046 46.24575)
3826,3821,16071,vij,3,FORWIND + Copernicus Emergency Service,https://mapping.emergency.copernicus.eu/activa...,,SI20200205,"Id of the Event, given as ISO2 + Date of storm",unclear salvage,high,POINT (14.39247 46.2441)
3827,3822,16076,vij,3,FORWIND + Copernicus Emergency Service,https://mapping.emergency.copernicus.eu/activa...,,SI20200205,"Id of the Event, given as ISO2 + Date of storm",,high,POINT (14.4381 46.25011)

In [58]:
events = labels.filter("is_event").select(
    "sample_id", "label", pl.col.start.alias("flag_date")
)
segments = (
    labels.filter(~pl.col.is_event)
    .unpivot(["start", "end"], index=["sample_id", "label"], value_name="flag_date")
    .drop("variable")
)
all_labels = pl.concat([events, segments])

In [59]:
all_labels

shape: (12_110, 3)
┌───────────┬───────┬─────────────────────────┐
│ sample_id ┆ label ┆ flag_date               │
│ ---       ┆ ---   ┆ ---                     │
│ u16       ┆ u16   ┆ datetime[ms, UTC]       │
╞═══════════╪═══════╪═════════════════════════╡
│ 0         ┆ 212   ┆ 2022-04-08 00:00:00 UTC │
│ 0         ┆ 211   ┆ 2024-04-02 00:00:00 UTC │
│ 1         ┆ 211   ┆ 2023-06-22 00:00:00 UTC │
│ 2         ┆ 212   ┆ 2022-04-08 00:00:00 UTC │
│ 3         ┆ 212   ┆ 2022-05-08 00:00:00 UTC │
│ …         ┆ …     ┆ …                       │
│ 3820      ┆ 120   ┆ 2024-12-30 00:00:00 UTC │
│ 3821      ┆ 110   ┆ 2020-01-21 00:00:00 UTC │
│ 3821      ┆ 121   ┆ 2024-12-30 00:00:00 UTC │
│ 3822      ┆ 110   ┆ 2020-01-21 00:00:00 UTC │
│ 3822      ┆ 120   ┆ 2024-12-30 00:00:00 UTC │
└───────────┴───────┴─────────────────────────┘

In [60]:
flags_tuple = (
    all_labels.filter(sample_id=0)
    .sort("flag_date")
    .select(pl.col.flag_date.dt.strftime("%Y-%m-%d"), "label")
    .rows_by_key("flag_date", unique=True)
)
flags = {k: str(v[0]) for k, v in flags_tuple.items()}

In [61]:
features = []
for row, f in samples.iterrows():
    sample_id = f["sample_id"]
    flags_tuple = (
        all_labels.filter(sample_id=sample_id)
        .sort("flag_date")
        .select(pl.col.flag_date.dt.strftime("%Y-%m-%d"), "label")
        .rows_by_key("flag_date", unique=True)
    )
    flags = {k: str(v[0]) for k, v in flags_tuple.items()}
    feature = {
        "type": "Feature",
        "geometry": {
            "type": "Point",
            "coordinates": [f["geometry"].x, f["geometry"].y],
        },
        "properties": {
            "sample_id": sample_id,
            "flags": flags,
            "confidence": f["confidence"],
            "cluster_id": f["cluster_id"],
            "source": f["source"],
            "comment": f["comment"],
            "interpreter": f["interpreter"],
        },
    }
    features.append(feature)

In [62]:
features

[{'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.122119320177979, 36.741785367381176]},
  'properties': {'sample_id': 0,
   'flags': {'2016-11-10': '110',
    '2022-03-09': '110',
    '2022-04-08': '212',
    '2024-04-02': '211'},
   'confidence': 'high',
   'cluster_id': '0.0',
   'source': 'EFFIS',
   'comment': 'border, thinning, then clear cut',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.121614665341534, 36.74231320914648]},
  'properties': {'sample_id': 1,
   'flags': {'2016-11-10': '110', '2023-05-03': '110', '2023-06-22': '211'},
   'confidence': 'medium',
   'cluster_id': '1.0',
   'source': 'EFFIS',
   'comment': 'unclear progression, edge',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.1191960120097075, 36.7420339745919]},
  'properties': {'sample_id': 2,
   'flags': {'2016-11-10': '110', '2022-04-01': '110', '2022-04-08': '212'},
   'confidence': 'high',
   'cluster_id': '2.0',
   'source': 'EFFIS',
   'comment': 'plantation',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.128450449507423, 36.758310257837195]},
  'properties': {'sample_id': 3,
   'flags': {'2016-11-10': '110', '2022-05-01': '110', '2022-05-08': '212'},
   'confidence': 'high',
   'cluster_id': '3.0',
   'source': 'EFFIS',
   'comment': 'plantation',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.128162488842775, 36.759080602148686]},
  'properties': {'sample_id': 4,
   'flags': {'2016-11-10': '110',
    '2020-05-03': '110',
    '2020-05-08': '211',
    '2020-11-29': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '5.0',
   'source': 'EFFIS',
   'comment': 'clear cut',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.129171681396344, 36.765070384909144]},
  'properties': {'sample_id': 5,
   'flags': {'2016-11-10': '110',
    '2021-05-15': '110',
    '2021-05-18': '211',
    '2022-12-19': '120',
    '2024-12-28': '120'},
   'confidence': 'high',
   'cluster_id': '7.0',
   'source': 'EFFIS',
   'comment': 'clear cut',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.131228629941185, 36.76562416158646]},
  'properties': {'sample_id': 6,
   'flags': {'2016-11-10': '110',
    '2020-05-03': '110',
    '2020-05-08': '211',
    '2021-05-28': '121'},
   'confidence': 'high',
   'cluster_id': '8.0',
   'source': 'EFFIS',
   'comment': 'plantation',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.12981939940043, 36.766058969812455]},
  'properties': {'sample_id': 7,
   'flags': {'2016-11-10': '110',
    '2020-05-18': '110',
    '2020-05-28': '211',
    '2021-09-15': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '9.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.135373605141477, 36.76932524209192]},
  'properties': {'sample_id': 8,
   'flags': {'2016-11-10': '123',
    '2019-09-01': '123',
    '2019-09-06': '213',
    '2019-10-06': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '10.0',
   'source': 'EFFIS',
   'comment': 'new plantation, no previous forest',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.13314612460277, 36.767927422622996]},
  'properties': {'sample_id': 9,
   'flags': {'2016-11-10': '123',
    '2021-04-08': '123',
    '2021-04-18': '213',
    '2021-12-04': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '11.0',
   'source': 'EFFIS',
   'comment': 'very low tcd, new plantation',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.134883415351279, 36.77274054635719]},
  'properties': {'sample_id': 10,
   'flags': {'2016-11-10': '110',
    '2019-04-29': '110',
    '2019-05-09': '211',
    '2020-06-07': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '12.0',
   'source': 'EFFIS',
   'comment': 'new plantation',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.122801075668697, 36.90866360137541]},
  'properties': {'sample_id': 11,
   'flags': {'2017-03-30': '110',
    '2021-04-15': '110',
    '2021-04-18': '211',
    '2021-07-22': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '13.0',
   'source': 'EFFIS',
   'comment': 'new plantation, low tcd start',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.135250037086163, 36.93894194006033]},
  'properties': {'sample_id': 12,
   'flags': {'2016-11-10': '110', '2021-04-01': '110', '2021-04-03': '211'},
   'confidence': 'high',
   'cluster_id': '14.0',
   'source': 'EFFIS',
   'comment': 'low tcd, no visible regreening',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.131257423881282, 36.93726473990329]},
  'properties': {'sample_id': 13,
   'flags': {'2016-11-10': '110',
    '2021-02-17': '110',
    '2021-02-22': '211',
    '2022-03-09': '120',
    '2024-12-28': '120'},
   'confidence': 'high',
   'cluster_id': '15.0',
   'source': 'EFFIS',
   'comment': 'might be lu conversion to agriculture',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.123071808229828, 36.91481942195458]},
  'properties': {'sample_id': 14,
   'flags': {'2017-03-30': '110',
    '2020-06-15': '110',
    '2020-06-17': '211',
    '2020-11-29': '120',
    '2024-12-28': '120'},
   'confidence': 'high',
   'cluster_id': '16.0',
   'source': 'EFFIS',
   'comment': 'possible lu change',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.138059006339472, 36.913511118205854]},
  'properties': {'sample_id': 15,
   'flags': {'2016-11-10': '110',
    '2020-09-25': '110',
    '2020-10-15': '211',
    '2020-12-24': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '17.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.138284628180522, 36.91307346910859]},
  'properties': {'sample_id': 16,
   'flags': {'2016-11-10': '110',
    '2020-10-15': '211',
    '2022-02-02': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '18.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.126252027648129, 36.90609761798644]},
  'properties': {'sample_id': 17,
   'flags': {'2016-11-10': '110',
    '2021-03-15': '110',
    '2021-03-19': '211',
    '2022-09-10': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '19.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.138919162922016, 36.89114106320266]},
  'properties': {'sample_id': 18,
   'flags': {'2016-11-10': '110', '2020-10-05': '110', '2020-10-10': '211'},
   'confidence': 'medium',
   'cluster_id': '20.0',
   'source': 'EFFIS',
   'comment': 'unclear after logging',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.143884923897603, 36.82162096537698]},
  'properties': {'sample_id': 19,
   'flags': {'2016-11-10': '110',
    '2020-12-15': '110',
    '2020-12-24': '211',
    '2022-03-09': '120',
    '2024-12-28': '120'},
   'confidence': 'high',
   'cluster_id': '22.0',
   'source': 'EFFIS',
   'comment': 'low TCD, possible luc',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.136940400350274, 36.808554779551805]},
  'properties': {'sample_id': 20,
   'flags': {'2016-11-10': '110',
    '2017-06-08': '110',
    '2017-07-03': '211',
    '2017-10-31': '121',
    '2021-05-13': '121',
    '2021-05-18': '220',
    '2022-12-24': '121',
    '2024-12-28': '121'},
   'confidence': 'medium',
   'cluster_id': '23.0',
   'source': 'EFFIS',
   'comment': 'low tcd, multiple cuts, plantation',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.149760872925842, 36.78775601277046]},
  'properties': {'sample_id': 21,
   'flags': {'2016-11-10': '110', '2020-01-19': '110', '2020-01-29': '211'},
   'confidence': 'high',
   'cluster_id': '24.0',
   'source': 'EFFIS',
   'comment': 'no visible recovery',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.134757232442436, 36.723920323909425]},
  'properties': {'sample_id': 22,
   'flags': {'2016-11-10': '110',
    '2018-10-16': '110',
    '2018-12-30': '211',
    '2019-06-18': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '25.0',
   'source': 'EFFIS',
   'comment': 'Durchforstung/Auflockerung 2019, Camping  nicht erkennbar',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.165644751365787, 36.731134389338706]},
  'properties': {'sample_id': 23,
   'flags': {'2016-11-10': '110',
    '2020-03-04': '110',
    '2020-03-29': '211',
    '2020-10-15': '121',
    '2024-12-28': '121'},
   'confidence': 'high',
   'cluster_id': '26.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.164797133014972, 36.731512624042374]},
  'properties': {'sample_id': 24,
   'flags': {'2016-11-10': '110',
    '2020-03-15': '110',
    '2020-03-29': '212',
    '2020-12-09': '122',
    '2024-12-28': '122'},
   'confidence': 'high',
   'cluster_id': '27.0',
   'source': 'EFFIS',
   'comment': 'border',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.132728039445068, 36.760866335551896]},
  'properties': {'sample_id': 25,
   'flags': {'2016-11-10': '110',
    '2018-04-04': '110',
    '2018-04-14': '212',
    '2018-11-30': '122',
    '2024-12-28': '122'},
   'confidence': 'high',
   'cluster_id': '28.0',
   'source': 'EFFIS',
   'comment': 'likely thinning',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.133542372186279, 36.75888291502763]},
  'properties': {'sample_id': 26,
   'flags': {'2016-11-10': '110',
    '2017-02-28': '110',
    '2017-04-19': '211',
    '2017-08-12': '121',
    '2021-01-13': '121'},
   'confidence': 'medium',
   'cluster_id': '29.0',
   'source': 'EFFIS',
   'comment': 'slow decline at the end',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-4.134520065871737, 36.75819298498123]},
  'properties': {'sample_id': 27,
   'flags': {'2016-11-10': '110',
    '2020-02-23': '110',
    '2020-02-28': '211',
    '2020-05-28': '121',
    '2023-04-03': '121'},
   'confidence': 'high',
   'cluster_id': '30.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.210986696205433, 36.461403668056654]},
  'properties': {'sample_id': 28,
   'flags': {'2019-01-09': '110',
    '2021-09-20': '110',
    '2021-09-25': '242',
    '2022-07-12': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '31.0',
   'source': 'EFFIS',
   'comment': 'low TCD, slow regreening',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.231577693377308, 36.48845712608928]},
  'properties': {'sample_id': 29,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2021-10-20': '120',
    '2024-01-08': '120'},
   'confidence': 'high',
   'cluster_id': '32.0',
   'source': 'EFFIS',
   'comment': 'very low level of regreening',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.232287818053259, 36.487078312624455]},
  'properties': {'sample_id': 30,
   'flags': {'2017-02-01': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2021-12-09': '120',
    '2023-12-14': '120'},
   'confidence': 'high',
   'cluster_id': '32.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.228845617325274, 36.49448387726421]},
  'properties': {'sample_id': 31,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-09-20': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '33.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.231911217009943, 36.49627425913136]},
  'properties': {'sample_id': 32,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2021-11-22': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '33.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.230086146745226, 36.4962081383078]},
  'properties': {'sample_id': 33,
   'flags': {'2016-11-03': '123',
    '2021-09-10': '123',
    '2021-09-18': '242',
    '2021-12-29': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '33.0',
   'source': 'EFFIS',
   'comment': 'no forest, border',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.229487509609377, 36.49325441742036]},
  'properties': {'sample_id': 34,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-02-15': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '33.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.194523633848678, 36.48980790968263]},
  'properties': {'sample_id': 35,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-03-12': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.193110296136662, 36.49065918002659]},
  'properties': {'sample_id': 36,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-05-06': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.189083158896929, 36.496129065379826]},
  'properties': {'sample_id': 37,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-10-05': '242',
    '2022-03-12': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.19143934922481, 36.49225643811705]},
  'properties': {'sample_id': 38,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-02-15': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.189210615424885, 36.49843302902132]},
  'properties': {'sample_id': 39,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-01': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.193930205161754, 36.49428144254875]},
  'properties': {'sample_id': 40,
   'flags': {'2015-07-12': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-02-10': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.188908544118779, 36.49958446050994]},
  'properties': {'sample_id': 41,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-02-22': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.192253681341349, 36.49031155238286]},
  'properties': {'sample_id': 42,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-08': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.189820151475181, 36.496898342749]},
  'properties': {'sample_id': 43,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-01': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.190018865061408, 36.4934680258976]},
  'properties': {'sample_id': 44,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-08': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.194948948676272, 36.49471862889232]},
  'properties': {'sample_id': 45,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-08': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.189190666404511, 36.493361050413]},
  'properties': {'sample_id': 46,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-08': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.193170775967886, 36.49493892998057]},
  'properties': {'sample_id': 47,
   'flags': {'2016-11-03': '110',
    '2021-09-10': '110',
    '2021-09-18': '242',
    '2022-04-08': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': '',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.196794295424005, 36.49092149594327]},
  'properties': {'sample_id': 48,
   'flags': {'2016-11-03': '123',
    '2021-09-10': '123',
    '2021-09-18': '242',
    '2022-03-02': '120',
    '2024-12-31': '120'},
   'confidence': 'high',
   'cluster_id': '34.0',
   'source': 'EFFIS',
   'comment': 'low TCD',
   'interpreter': 'vij'}},
 {'type': 'Feature',
  'geometry': {'type': 'Point',
   'coordinates': [-5.189020611585112, 36.49189054168373]},
  'properties': {'sample_id': 49,
   'flags': {'2016-11-03': '110',

In [63]:
campaign_setup["features"] = features

In [64]:
with open("test.geojson", "w") as fp:
    json.dump(campaign_setup, fp, indent=4)

In [65]:
with open("test.geojson", "r") as fp:
    campaign_setup = json.load(fp)

In [66]:
campaign_setup

{'type': 'FeatureCollection',
 'campaign': {'name': 'DISFOR',
  'startDate': '2015-01-01',
  'endDate': '2025-01-31',
  'flagLabels': {'100': 'Healthy Vegetation',
   '110': 'Undisturbed Forest',
   '120': 'Revegetation',
   '121': 'With Trees (after clear cut)',
   '122': 'Canopy closing (after thinning/defoliation)',
   '123': 'Without Trees (shrubs and grasses, no reforestation visible)',
   '200': 'Disturbed',
   '210': 'Planned',
   '211': 'Clear Cut',
   '212': 'Thinning',
   '213': 'Forestry Mulching (Non Forest Vegetation Removal)',
   '220': 'Salvage',
   '221': 'After Biotic Disturbance',
   '222': 'After Abiotic Disturbance',
   '230': 'Biotic',
   '231': 'Bark Beetle (with decline)',
   '232': 'Gypsy Moth (temporary)',
   '240': 'Abiotic',
   '241': 'Drought',
   '242': 'Wildfire',
   '243': 'Wind',
   '244': 'Avalanche',
   '245': 'Flood'},
  'fields': [{'key': 'sample_id',
    'label': 'Sample ID',
    'type': 'display',
    'required': True,
    'session_persistent': False},
   {'key': 'source',
    'label': 'Source',
    'type': 'display',
    'required': True,
    'session_persistent': False},
   {'key': 'cluster_id',
    'label': 'Cluster ID',
    'type': 'display',
    'required': True,
    'session_persistent': False},
   {'key': 'confidence',
    'label': 'Confidence',
    'type': 'select',
    'options': ['high', 'medium', 'low'],
    'required': True,
    'session_persistent': False},
   {'key': 'comment',
    'label': 'Comment',
    'type': 'text',
    'required': False,
    'session_persistent': False},
   {'key': 'interpreter',
    'label': 'Interpreter',
    'type': 'text',
    'required': True,
    'session_persistent': True}]},
 'features': [{'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.122119320177979, 36.741785367381176]},
   'properties': {'sample_id': 0,
    'flags': {'2016-11-10': '110',
     '2022-03-09': '110',
     '2022-04-08': '212',
     '2024-04-02': '211'},
    'confidence': 'high',
    'cluster_id': '0.0',
    'source': 'EFFIS',
    'comment': 'border, thinning, then clear cut',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.121614665341534, 36.74231320914648]},
   'properties': {'sample_id': 1,
    'flags': {'2016-11-10': '110', '2023-05-03': '110', '2023-06-22': '211'},
    'confidence': 'medium',
    'cluster_id': '1.0',
    'source': 'EFFIS',
    'comment': 'unclear progression, edge',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.1191960120097075, 36.7420339745919]},
   'properties': {'sample_id': 2,
    'flags': {'2016-11-10': '110', '2022-04-01': '110', '2022-04-08': '212'},
    'confidence': 'high',
    'cluster_id': '2.0',
    'source': 'EFFIS',
    'comment': 'plantation',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.128450449507423, 36.758310257837195]},
   'properties': {'sample_id': 3,
    'flags': {'2016-11-10': '110', '2022-05-01': '110', '2022-05-08': '212'},
    'confidence': 'high',
    'cluster_id': '3.0',
    'source': 'EFFIS',
    'comment': 'plantation',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.128162488842775, 36.759080602148686]},
   'properties': {'sample_id': 4,
    'flags': {'2016-11-10': '110',
     '2020-05-03': '110',
     '2020-05-08': '211',
     '2020-11-29': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '5.0',
    'source': 'EFFIS',
    'comment': 'clear cut',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.129171681396344, 36.765070384909144]},
   'properties': {'sample_id': 5,
    'flags': {'2016-11-10': '110',
     '2021-05-15': '110',
     '2021-05-18': '211',
     '2022-12-19': '120',
     '2024-12-28': '120'},
    'confidence': 'high',
    'cluster_id': '7.0',
    'source': 'EFFIS',
    'comment': 'clear cut',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.131228629941185, 36.76562416158646]},
   'properties': {'sample_id': 6,
    'flags': {'2016-11-10': '110',
     '2020-05-03': '110',
     '2020-05-08': '211',
     '2021-05-28': '121'},
    'confidence': 'high',
    'cluster_id': '8.0',
    'source': 'EFFIS',
    'comment': 'plantation',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.12981939940043, 36.766058969812455]},
   'properties': {'sample_id': 7,
    'flags': {'2016-11-10': '110',
     '2020-05-18': '110',
     '2020-05-28': '211',
     '2021-09-15': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '9.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.135373605141477, 36.76932524209192]},
   'properties': {'sample_id': 8,
    'flags': {'2016-11-10': '123',
     '2019-09-01': '123',
     '2019-09-06': '213',
     '2019-10-06': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '10.0',
    'source': 'EFFIS',
    'comment': 'new plantation, no previous forest',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.13314612460277, 36.767927422622996]},
   'properties': {'sample_id': 9,
    'flags': {'2016-11-10': '123',
     '2021-04-08': '123',
     '2021-04-18': '213',
     '2021-12-04': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '11.0',
    'source': 'EFFIS',
    'comment': 'very low tcd, new plantation',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.134883415351279, 36.77274054635719]},
   'properties': {'sample_id': 10,
    'flags': {'2016-11-10': '110',
     '2019-04-29': '110',
     '2019-05-09': '211',
     '2020-06-07': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '12.0',
    'source': 'EFFIS',
    'comment': 'new plantation',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.122801075668697, 36.90866360137541]},
   'properties': {'sample_id': 11,
    'flags': {'2017-03-30': '110',
     '2021-04-15': '110',
     '2021-04-18': '211',
     '2021-07-22': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '13.0',
    'source': 'EFFIS',
    'comment': 'new plantation, low tcd start',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.135250037086163, 36.93894194006033]},
   'properties': {'sample_id': 12,
    'flags': {'2016-11-10': '110', '2021-04-01': '110', '2021-04-03': '211'},
    'confidence': 'high',
    'cluster_id': '14.0',
    'source': 'EFFIS',
    'comment': 'low tcd, no visible regreening',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.131257423881282, 36.93726473990329]},
   'properties': {'sample_id': 13,
    'flags': {'2016-11-10': '110',
     '2021-02-17': '110',
     '2021-02-22': '211',
     '2022-03-09': '120',
     '2024-12-28': '120'},
    'confidence': 'high',
    'cluster_id': '15.0',
    'source': 'EFFIS',
    'comment': 'might be lu conversion to agriculture',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.123071808229828, 36.91481942195458]},
   'properties': {'sample_id': 14,
    'flags': {'2017-03-30': '110',
     '2020-06-15': '110',
     '2020-06-17': '211',
     '2020-11-29': '120',
     '2024-12-28': '120'},
    'confidence': 'high',
    'cluster_id': '16.0',
    'source': 'EFFIS',
    'comment': 'possible lu change',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.138059006339472, 36.913511118205854]},
   'properties': {'sample_id': 15,
    'flags': {'2016-11-10': '110',
     '2020-09-25': '110',
     '2020-10-15': '211',
     '2020-12-24': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '17.0',
    'source': 'EFFIS',
    'comment': 'low TCD',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.138284628180522, 36.91307346910859]},
   'properties': {'sample_id': 16,
    'flags': {'2016-11-10': '110',
     '2020-10-15': '211',
     '2022-02-02': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '18.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.126252027648129, 36.90609761798644]},
   'properties': {'sample_id': 17,
    'flags': {'2016-11-10': '110',
     '2021-03-15': '110',
     '2021-03-19': '211',
     '2022-09-10': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '19.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.138919162922016, 36.89114106320266]},
   'properties': {'sample_id': 18,
    'flags': {'2016-11-10': '110', '2020-10-05': '110', '2020-10-10': '211'},
    'confidence': 'medium',
    'cluster_id': '20.0',
    'source': 'EFFIS',
    'comment': 'unclear after logging',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.143884923897603, 36.82162096537698]},
   'properties': {'sample_id': 19,
    'flags': {'2016-11-10': '110',
     '2020-12-15': '110',
     '2020-12-24': '211',
     '2022-03-09': '120',
     '2024-12-28': '120'},
    'confidence': 'high',
    'cluster_id': '22.0',
    'source': 'EFFIS',
    'comment': 'low TCD, possible luc',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.136940400350274, 36.808554779551805]},
   'properties': {'sample_id': 20,
    'flags': {'2016-11-10': '110',
     '2017-06-08': '110',
     '2017-07-03': '211',
     '2017-10-31': '121',
     '2021-05-13': '121',
     '2021-05-18': '220',
     '2022-12-24': '121',
     '2024-12-28': '121'},
    'confidence': 'medium',
    'cluster_id': '23.0',
    'source': 'EFFIS',
    'comment': 'low tcd, multiple cuts, plantation',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.149760872925842, 36.78775601277046]},
   'properties': {'sample_id': 21,
    'flags': {'2016-11-10': '110', '2020-01-19': '110', '2020-01-29': '211'},
    'confidence': 'high',
    'cluster_id': '24.0',
    'source': 'EFFIS',
    'comment': 'no visible recovery',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.134757232442436, 36.723920323909425]},
   'properties': {'sample_id': 22,
    'flags': {'2016-11-10': '110',
     '2018-10-16': '110',
     '2018-12-30': '211',
     '2019-06-18': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '25.0',
    'source': 'EFFIS',
    'comment': 'Durchforstung/Auflockerung 2019, Camping  nicht erkennbar',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.165644751365787, 36.731134389338706]},
   'properties': {'sample_id': 23,
    'flags': {'2016-11-10': '110',
     '2020-03-04': '110',
     '2020-03-29': '211',
     '2020-10-15': '121',
     '2024-12-28': '121'},
    'confidence': 'high',
    'cluster_id': '26.0',
    'source': 'EFFIS',
    'comment': 'low TCD',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.164797133014972, 36.731512624042374]},
   'properties': {'sample_id': 24,
    'flags': {'2016-11-10': '110',
     '2020-03-15': '110',
     '2020-03-29': '212',
     '2020-12-09': '122',
     '2024-12-28': '122'},
    'confidence': 'high',
    'cluster_id': '27.0',
    'source': 'EFFIS',
    'comment': 'border',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.132728039445068, 36.760866335551896]},
   'properties': {'sample_id': 25,
    'flags': {'2016-11-10': '110',
     '2018-04-04': '110',
     '2018-04-14': '212',
     '2018-11-30': '122',
     '2024-12-28': '122'},
    'confidence': 'high',
    'cluster_id': '28.0',
    'source': 'EFFIS',
    'comment': 'likely thinning',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.133542372186279, 36.75888291502763]},
   'properties': {'sample_id': 26,
    'flags': {'2016-11-10': '110',
     '2017-02-28': '110',
     '2017-04-19': '211',
     '2017-08-12': '121',
     '2021-01-13': '121'},
    'confidence': 'medium',
    'cluster_id': '29.0',
    'source': 'EFFIS',
    'comment': 'slow decline at the end',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-4.134520065871737, 36.75819298498123]},
   'properties': {'sample_id': 27,
    'flags': {'2016-11-10': '110',
     '2020-02-23': '110',
     '2020-02-28': '211',
     '2020-05-28': '121',
     '2023-04-03': '121'},
    'confidence': 'high',
    'cluster_id': '30.0',
    'source': 'EFFIS',
    'comment': 'low TCD',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.210986696205433, 36.461403668056654]},
   'properties': {'sample_id': 28,
    'flags': {'2019-01-09': '110',
     '2021-09-20': '110',
     '2021-09-25': '242',
     '2022-07-12': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '31.0',
    'source': 'EFFIS',
    'comment': 'low TCD, slow regreening',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.231577693377308, 36.48845712608928]},
   'properties': {'sample_id': 29,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2021-10-20': '120',
     '2024-01-08': '120'},
    'confidence': 'high',
    'cluster_id': '32.0',
    'source': 'EFFIS',
    'comment': 'very low level of regreening',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.232287818053259, 36.487078312624455]},
   'properties': {'sample_id': 30,
    'flags': {'2017-02-01': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2021-12-09': '120',
     '2023-12-14': '120'},
    'confidence': 'high',
    'cluster_id': '32.0',
    'source': 'EFFIS',
    'comment': 'low TCD',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.228845617325274, 36.49448387726421]},
   'properties': {'sample_id': 31,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-09-20': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '33.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.231911217009943, 36.49627425913136]},
   'properties': {'sample_id': 32,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2021-11-22': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '33.0',
    'source': 'EFFIS',
    'comment': 'low TCD',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.230086146745226, 36.4962081383078]},
   'properties': {'sample_id': 33,
    'flags': {'2016-11-03': '123',
     '2021-09-10': '123',
     '2021-09-18': '242',
     '2021-12-29': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '33.0',
    'source': 'EFFIS',
    'comment': 'no forest, border',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.229487509609377, 36.49325441742036]},
   'properties': {'sample_id': 34,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-02-15': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '33.0',
    'source': 'EFFIS',
    'comment': 'low TCD',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.194523633848678, 36.48980790968263]},
   'properties': {'sample_id': 35,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-03-12': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.193110296136662, 36.49065918002659]},
   'properties': {'sample_id': 36,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-05-06': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.189083158896929, 36.496129065379826]},
   'properties': {'sample_id': 37,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-10-05': '242',
     '2022-03-12': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.19143934922481, 36.49225643811705]},
   'properties': {'sample_id': 38,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-02-15': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.189210615424885, 36.49843302902132]},
   'properties': {'sample_id': 39,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-04-01': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.193930205161754, 36.49428144254875]},
   'properties': {'sample_id': 40,
    'flags': {'2015-07-12': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-02-10': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.188908544118779, 36.49958446050994]},
   'properties': {'sample_id': 41,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-02-22': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.192253681341349, 36.49031155238286]},
   'properties': {'sample_id': 42,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-04-08': '120',
     '2024-12-31': '120'},
    'confidence': 'high',
    'cluster_id': '34.0',
    'source': 'EFFIS',
    'comment': '',
    'interpreter': 'vij'}},
  {'type': 'Feature',
   'geometry': {'type': 'Point',
    'coordinates': [-5.189820151475181, 36.496898342749]},
   'properties': {'sample_id': 43,
    'flags': {'2016-11-03': '110',
     '2021-09-10': '110',
     '2021-09-18': '242',
     '2022-04-01': '120',
     '2024-12-31': '120'},

In [67]:
campaign_schema = campaign_setup["campaign"]
campaign_schema

{'name': 'DISFOR',
 'startDate': '2015-01-01',
 'endDate': '2025-01-31',
 'flagLabels': {'100': 'Healthy Vegetation',
  '110': 'Undisturbed Forest',
  '120': 'Revegetation',
  '121': 'With Trees (after clear cut)',
  '122': 'Canopy closing (after thinning/defoliation)',
  '123': 'Without Trees (shrubs and grasses, no reforestation visible)',
  '200': 'Disturbed',
  '210': 'Planned',
  '211': 'Clear Cut',
  '212': 'Thinning',
  '213': 'Forestry Mulching (Non Forest Vegetation Removal)',
  '220': 'Salvage',
  '221': 'After Biotic Disturbance',
  '222': 'After Abiotic Disturbance',
  '230': 'Biotic',
  '231': 'Bark Beetle (with decline)',
  '232': 'Gypsy Moth (temporary)',
  '240': 'Abiotic',
  '241': 'Drought',
  '242': 'Wildfire',
  '243': 'Wind',
  '244': 'Avalanche',
  '245': 'Flood'},
 'fields': [{'key': 'sample_id',
   'label': 'Sample ID',
   'type': 'display',
   'required': True,
   'session_persistent': False},
  {'key': 'source',
   'label': 'Source',
   'type': 'display',
   'required': True,
   'session_persistent': False},
  {'key': 'cluster_id',
   'label': 'Cluster ID',
   'type': 'display',
   'required': True,
   'session_persistent': False},
  {'key': 'confidence',
   'label': 'Confidence',
   'type': 'select',
   'options': ['high', 'medium', 'low'],
   'required': True,
   'session_persistent': False},
  {'key': 'comment',
   'label': 'Comment',
   'type': 'text',
   'required': False,
   'session_persistent': False},
  {'key': 'interpreter',
   'label': 'Interpreter',
   'type': 'text',
   'required': True,
   'session_persistent': True}]}

In [68]:
# convert features in campaign to urls:

base_url = "https://cdse-tsbrowser.jonasvieh.workers.dev/?"

In [69]:
query_params = {}

In [70]:
query_params["start"] = campaign_schema.pop("startDate")
query_params["end"] = campaign_schema.pop("endDate")
campaign_schema["campaign"] = campaign_schema.pop("name")

In [71]:
query_params["schema"] = json.dumps(campaign_schema, separators=(",", ":"))

In [ ]:
urls = []
for feature in campaign_setup["features"]:
    query_params["lon"] = feature["geometry"]["coordinates"][0]
    query_params["lat"] = feature["geometry"]["coordinates"][1]
    query_params["sample"] = json.dumps(feature["properties"], separators=(",", ":"))
    urls.append(
        {
            "sample_id": feature["properties"]["sample_id"],
            "url": base_url + urllib.parse.urlencode(query_params),
        }
    )

In [91]:
pl.DataFrame(urls)

shape: (3_822, 2)
┌───────────┬─────────────────────────────────┐
│ sample_id ┆ url                             │
│ ---       ┆ ---                             │
│ i64       ┆ str                             │
╞═══════════╪═════════════════════════════════╡
│ 0         ┆ https://cdse-tsbrowser.jonasvi… │
│ 1         ┆ https://cdse-tsbrowser.jonasvi… │
│ 2         ┆ https://cdse-tsbrowser.jonasvi… │
│ 3         ┆ https://cdse-tsbrowser.jonasvi… │
│ 4         ┆ https://cdse-tsbrowser.jonasvi… │
│ …         ┆ …                               │
│ 3818      ┆ https://cdse-tsbrowser.jonasvi… │
│ 3819      ┆ https://cdse-tsbrowser.jonasvi… │
│ 3820      ┆ https://cdse-tsbrowser.jonasvi… │
│ 3821      ┆ https://cdse-tsbrowser.jonasvi… │
│ 3822      ┆ https://cdse-tsbrowser.jonasvi… │
└───────────┴─────────────────────────────────┘